version: "3.9"

services:
  vscode:
    image: codercom/code-server
    container_name: vscode
    ports:
      - "8443:8080"
    networks:
      - shared-net
    volumes:
      - shared-data:/shared  # Dossier commun monté dans /shared
      - vscode-data:/home/coder/.local/share/code-server

  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    networks:
      - shared-net
    volumes:
      - shared-data:/shared  # Même point de montage côté Jupyter
      - jupyter-data:/home/data
networks:
  shared-net:

volumes:
  shared-data:  # Volume partagé
  vscode-data:  # Données persistantes de VSCode (config, extensions)
  jupyter-data:  # Données persistantes de Jupyter (notebooks)
