version: "3.9"

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vscode
    ports:
      - "8443:8080"
    networks:
      - shared-net
    volumes:
      - shared-data:/shared
      - vscode-data:/home/coder/.local/share/code-server

  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    networks:
      - shared-net
    volumes:
      - shared-data:/shared
      - jupyter-data:/home/data
networks:
  shared-net:

volumes:
  shared-data:
  vscode-data:
  jupyter-data:
